import { Survey, AvatarOption, ResultSummary } from './types';

export const AVATARS: AvatarOption[] = [
  {
    id: 'zippy',
    name: 'Zippy',
    theme: 'Energetic Explorer',
    primaryColor: '#F97316',
    bgColor: '#FFF3C4',
  },
  {
    id: 'nova',
    name: 'Nova',
    theme: 'Curious Dreamer',
    primaryColor: '#5FA8F5',
    bgColor: '#EFF6FF',
  },
  {
    id: 'milo',
    name: 'Milo',
    theme: 'Friendly Adventurer',
    primaryColor: '#15803D',
    bgColor: '#DCFCE7',
  },
  {
    id: 'sunny',
    name: 'Sunny',
    theme: 'Bright & Bold',
    primaryColor: '#EA580C',
    bgColor: '#FFF7ED',
  },
  {
    id: 'jax',
    name: 'Jax',
    theme: 'Cool & Confident',
    primaryColor: '#DC2626',
    bgColor: '#FEF2F2',
  },
  {
    id: 'luna',
    name: 'Luna',
    theme: 'Creative Spirit',
    primaryColor: '#7C3AED',
    bgColor: '#F5F3FF',
  },
];

export const SAMPLE_SURVEYS: Survey[] = [
  {
    id: 'survey-1',
    title: 'How Was Your Week?',
    description: 'A quick check-in about your week at the program.',
    emoji: '⭐',
    color: '#6C4DF6',
    audience: 'youth',
    is_active: true,
    response_count: 47,
    completion_rate: 89,
    created_at: '2026-04-10T10:00:00Z',
    questions: [
      {
        id: 'q1',
        text: 'How are you feeling today?',
        type: 'emoji_rating',
        required: true,
        points: 10,
        options: [
          { id: 'awful', text: 'Awful', emoji: '😢' },
          { id: 'bad', text: 'Not Great', emoji: '😕' },
          { id: 'okay', text: 'Okay', emoji: '😐' },
          { id: 'good', text: 'Good', emoji: '😊' },
          { id: 'great', text: 'Amazing!', emoji: '🤩' },
        ],
      },
      {
        id: 'q2',
        text: 'What was the best part of this week?',
        type: 'multiple_choice',
        required: true,
        points: 10,
        options: [
          { id: 'friends', text: 'Hanging out with friends', emoji: '👫' },
          { id: 'activities', text: 'The activities we did', emoji: '🎨' },
          { id: 'learned', text: 'Something I learned', emoji: '📚' },
          { id: 'food', text: 'The snacks!', emoji: '🍕' },
          { id: 'other', text: 'Something else', emoji: '✨' },
        ],
      },
      {
        id: 'q3',
        text: 'Did you feel safe this week?',
        type: 'yes_no',
        required: true,
        points: 10,
        options: [
          { id: 'yes', text: 'Yes', emoji: '✅' },
          { id: 'no', text: 'No', emoji: '❌' },
        ],
      },
      {
        id: 'q4',
        text: 'How much did you enjoy the program this week?',
        type: 'scale',
        required: true,
        points: 10,
        options: [
          { id: '1', text: '1', emoji: '' },
          { id: '2', text: '2', emoji: '' },
          { id: '3', text: '3', emoji: '' },
          { id: '4', text: '4', emoji: '' },
          { id: '5', text: '5', emoji: '' },
        ],
      },
      {
        id: 'q5',
        text: 'Would you recommend this program to a friend?',
        type: 'yes_no',
        required: true,
        points: 10,
        options: [
          { id: 'yes', text: 'Yes!', emoji: '👍' },
          { id: 'no', text: 'Not yet', emoji: '👎' },
        ],
      },
    ],
  },
  {
    id: 'survey-2',
    title: 'Summer Camp Check-In',
    description: 'Tell us how camp is going for you!',
    emoji: '🏕️',
    color: '#5FA8F5',
    audience: 'youth',
    is_active: true,
    response_count: 31,
    completion_rate: 94,
    created_at: '2026-04-15T10:00:00Z',
    questions: [
      {
        id: 'q1',
        text: 'How excited are you about camp today?',
        type: 'emoji_rating',
        required: true,
        points: 10,
        options: [
          { id: 'not', text: 'Not at all', emoji: '😴' },
          { id: 'little', text: 'A little', emoji: '🙂' },
          { id: 'some', text: 'Pretty excited', emoji: '😁' },
          { id: 'very', text: 'Super excited!', emoji: '🤩' },
        ],
      },
      {
        id: 'q2',
        text: 'Which camp activity is your favorite?',
        type: 'multiple_choice',
        required: true,
        points: 10,
        options: [
          { id: 'swim', text: 'Swimming', emoji: '🏊' },
          { id: 'craft', text: 'Arts & Crafts', emoji: '🎨' },
          { id: 'sport', text: 'Sports', emoji: '⚽' },
          { id: 'nature', text: 'Nature Walks', emoji: '🌳' },
          { id: 'music', text: 'Music', emoji: '🎵' },
        ],
      },
      {
        id: 'q3',
        text: 'Have you made a new friend at camp?',
        type: 'yes_no',
        required: true,
        points: 10,
        options: [
          { id: 'yes', text: 'Yes!', emoji: '👏' },
          { id: 'no', text: 'Not yet', emoji: '🤞' },
        ],
      },
    ],
  },
  {
    id: 'survey-3',
    title: 'Monthly Wellbeing Check',
    description: "A monthly snapshot of how you're doing.",
    emoji: '💙',
    color: '#FFC72C',
    audience: 'youth',
    is_active: false,
    response_count: 62,
    completion_rate: 78,
    created_at: '2026-03-01T10:00:00Z',
    questions: [
      {
        id: 'q1',
        text: 'Overall, how are you doing this month?',
        type: 'emoji_rating',
        required: true,
        points: 10,
        options: [
          { id: 'awful', text: 'Struggling', emoji: '😢' },
          { id: 'bad', text: 'Tough times', emoji: '😕' },
          { id: 'okay', text: 'Getting by', emoji: '😐' },
          { id: 'good', text: 'Doing well', emoji: '😊' },
          { id: 'great', text: 'Thriving!', emoji: '🌟' },
        ],
      },
    ],
  },
  {
    id: 'survey-4',
    title: 'Staff Experience Survey',
    description: 'Share your experience working with our program this quarter.',
    emoji: '📋',
    color: '#6C4DF6',
    audience: 'adult',
    is_active: true,
    response_count: 18,
    completion_rate: 83,
    created_at: '2026-04-01T10:00:00Z',
    questions: [
      {
        id: 'q1',
        text: 'How satisfied are you with your role at the organization?',
        type: 'scale',
        required: true,
        points: 0,
        options: [
          { id: '1', text: '1 — Very dissatisfied', emoji: '' },
          { id: '2', text: '2', emoji: '' },
          { id: '3', text: '3 — Neutral', emoji: '' },
          { id: '4', text: '4', emoji: '' },
          { id: '5', text: '5 — Very satisfied', emoji: '' },
        ],
      },
      {
        id: 'q2',
        text: 'Which area do you feel needs the most improvement?',
        type: 'multiple_choice',
        required: true,
        points: 0,
        options: [
          { id: 'training', text: 'Staff training & development', emoji: '' },
          { id: 'communication', text: 'Internal communication', emoji: '' },
          { id: 'resources', text: 'Program resources & materials', emoji: '' },
          { id: 'support', text: 'Management support', emoji: '' },
          { id: 'other', text: 'Other', emoji: '' },
        ],
      },
      {
        id: 'q3',
        text: 'Do you feel equipped to support youth participants effectively?',
        type: 'yes_no',
        required: true,
        points: 0,
        options: [
          { id: 'yes', text: 'Yes', emoji: '' },
          { id: 'no', text: 'Not fully', emoji: '' },
        ],
      },
      {
        id: 'q4',
        text: 'How would you rate team collaboration this quarter?',
        type: 'emoji_rating',
        required: true,
        points: 0,
        options: [
          { id: '1', text: 'Poor', emoji: '😟' },
          { id: '2', text: 'Below average', emoji: '😐' },
          { id: '3', text: 'Average', emoji: '🙂' },
          { id: '4', text: 'Good', emoji: '😊' },
          { id: '5', text: 'Excellent', emoji: '🌟' },
        ],
      },
      {
        id: 'q5',
        text: 'Would you recommend this organization as a great place to work?',
        type: 'yes_no',
        required: true,
        points: 0,
        options: [
          { id: 'yes', text: 'Yes', emoji: '' },
          { id: 'no', text: 'Not right now', emoji: '' },
        ],
      },
    ],
  },
  {
    id: 'survey-5',
    title: 'Caregiver Feedback Form',
    description: 'Help us improve our program by sharing your perspective as a caregiver.',
    emoji: '🤝',
    color: '#5FA8F5',
    audience: 'adult',
    is_active: true,
    response_count: 24,
    completion_rate: 91,
    created_at: '2026-04-20T10:00:00Z',
    questions: [
      {
        id: 'q1',
        text: 'Overall, how satisfied are you with our program?',
        type: 'scale',
        required: true,
        points: 0,
        options: [
          { id: '1', text: '1 — Very dissatisfied', emoji: '' },
          { id: '2', text: '2', emoji: '' },
          { id: '3', text: '3 — Neutral', emoji: '' },
          { id: '4', text: '4', emoji: '' },
          { id: '5', text: '5 — Very satisfied', emoji: '' },
        ],
      },
      {
        id: 'q2',
        text: 'Has participating in this program positively impacted your child or youth?',
        type: 'yes_no',
        required: true,
        points: 0,
        options: [
          { id: 'yes', text: 'Yes', emoji: '' },
          { id: 'no', text: 'Not that I\'ve noticed', emoji: '' },
        ],
      },
      {
        id: 'q3',
        text: 'Which aspect of the program do you value most?',
        type: 'multiple_choice',
        required: true,
        points: 0,
        options: [
          { id: 'safety', text: 'Safe, supervised environment', emoji: '' },
          { id: 'learning', text: 'Educational opportunities', emoji: '' },
          { id: 'social', text: 'Social development', emoji: '' },
          { id: 'enrichment', text: 'Arts & enrichment activities', emoji: '' },
          { id: 'support', text: 'Family support & resources', emoji: '' },
        ],
      },
    ],
  },
];

export const SAMPLE_RESULTS: Record<string, ResultSummary[]> = {
  'survey-1': [
    {
      question_id: 'q1',
      question_text: 'How are you feeling today?',
      type: 'emoji_rating',
      total_responses: 47,
      answers: [
        { label: '😢 Awful', count: 2, percentage: 4 },
        { label: '😕 Not Great', count: 4, percentage: 9 },
        { label: '😐 Okay', count: 8, percentage: 17 },
        { label: '😊 Good', count: 18, percentage: 38 },
        { label: '🤩 Amazing!', count: 15, percentage: 32 },
      ],
    },
    {
      question_id: 'q2',
      question_text: 'What was the best part of this week?',
      type: 'multiple_choice',
      total_responses: 47,
      answers: [
        { label: '👫 Hanging out with friends', count: 19, percentage: 40 },
        { label: '🎨 The activities we did', count: 14, percentage: 30 },
        { label: '📚 Something I learned', count: 7, percentage: 15 },
        { label: '🍕 The snacks!', count: 5, percentage: 11 },
        { label: '✨ Something else', count: 2, percentage: 4 },
      ],
    },
    {
      question_id: 'q3',
      question_text: 'Did you feel safe this week?',
      type: 'yes_no',
      total_responses: 47,
      answers: [
        { label: 'Yes', count: 45, percentage: 96 },
        { label: 'No', count: 2, percentage: 4 },
      ],
    },
    {
      question_id: 'q4',
      question_text: 'How much did you enjoy the program this week?',
      type: 'scale',
      total_responses: 47,
      answers: [
        { label: '1', count: 1, percentage: 2 },
        { label: '2', count: 2, percentage: 4 },
        { label: '3', count: 7, percentage: 15 },
        { label: '4', count: 16, percentage: 34 },
        { label: '5', count: 21, percentage: 45 },
      ],
    },
    {
      question_id: 'q5',
      question_text: 'Would you recommend this program to a friend?',
      type: 'yes_no',
      total_responses: 47,
      answers: [
        { label: 'Yes!', count: 43, percentage: 91 },
        { label: 'Not yet', count: 4, percentage: 9 },
      ],
    },
  ],
  'survey-4': [
    {
      question_id: 'q1',
      question_text: 'How satisfied are you with your role at the organization?',
      type: 'scale',
      total_responses: 18,
      answers: [
        { label: '1 — Very dissatisfied', count: 0, percentage: 0 },
        { label: '2', count: 1, percentage: 6 },
        { label: '3 — Neutral', count: 3, percentage: 17 },
        { label: '4', count: 8, percentage: 44 },
        { label: '5 — Very satisfied', count: 6, percentage: 33 },
      ],
    },
    {
      question_id: 'q2',
      question_text: 'Which area do you feel needs the most improvement?',
      type: 'multiple_choice',
      total_responses: 18,
      answers: [
        { label: 'Staff training & development', count: 7, percentage: 39 },
        { label: 'Internal communication', count: 5, percentage: 28 },
        { label: 'Program resources & materials', count: 4, percentage: 22 },
        { label: 'Management support', count: 1, percentage: 6 },
        { label: 'Other', count: 1, percentage: 6 },
      ],
    },
    {
      question_id: 'q3',
      question_text: 'Do you feel equipped to support youth participants effectively?',
      type: 'yes_no',
      total_responses: 18,
      answers: [
        { label: 'Yes', count: 13, percentage: 72 },
        { label: 'Not fully', count: 5, percentage: 28 },
      ],
    },
    {
      question_id: 'q4',
      question_text: 'How would you rate team collaboration this quarter?',
      type: 'emoji_rating',
      total_responses: 18,
      answers: [
        { label: '😟 Poor', count: 0, percentage: 0 },
        { label: '😐 Below average', count: 1, percentage: 6 },
        { label: '🙂 Average', count: 3, percentage: 17 },
        { label: '😊 Good', count: 9, percentage: 50 },
        { label: '🌟 Excellent', count: 5, percentage: 28 },
      ],
    },
    {
      question_id: 'q5',
      question_text: 'Would you recommend this organization as a great place to work?',
      type: 'yes_no',
      total_responses: 18,
      answers: [
        { label: 'Yes', count: 15, percentage: 83 },
        { label: 'Not right now', count: 3, percentage: 17 },
      ],
    },
  ],
};

export const DEMO_SURVEYS: Survey[] = [
  {
    id: 'demo-kids',
    title: 'How Did Today Go?',
    description: 'A quick check-in just for you. Pick your character and let us know!',
    emoji: '🌟',
    color: '#7C3AED',
    audience: 'youth',
    is_active: true,
    response_count: 0,
    completion_rate: 0,
    created_at: '2026-04-26T00:00:00Z',
    questions: [
      {
        id: 'dq1',
        text: 'How are you feeling today?',
        type: 'emoji_rating',
        required: true,
        points: 10,
        options: [
          { id: 'awful', text: 'Not good', emoji: '😢' },
          { id: 'meh', text: 'Meh', emoji: '😕' },
          { id: 'okay', text: 'Okay', emoji: '😐' },
          { id: 'good', text: 'Good!', emoji: '😊' },
          { id: 'great', text: 'Amazing!', emoji: '🤩' },
        ],
      },
      {
        id: 'dq2',
        text: 'Which activity did you like best?',
        type: 'multiple_choice',
        required: true,
        points: 10,
        options: [
          { id: 'art', text: 'Arts & Crafts', emoji: '🎨' },
          { id: 'sports', text: 'Sports & Games', emoji: '⚽' },
          { id: 'music', text: 'Music', emoji: '🎵' },
          { id: 'reading', text: 'Reading & Stories', emoji: '📚' },
          { id: 'outdoors', text: 'Being Outdoors', emoji: '🌳' },
        ],
      },
      {
        id: 'dq3',
        text: 'Pick the badge that matches your experience today!',
        type: 'multiple_choice',
        required: true,
        points: 10,
        options: [
          { id: 'explorer', text: 'Explorer', emoji: '🗺️' },
          { id: 'champion', text: 'Champion', emoji: '🏆' },
          { id: 'creator', text: 'Creator', emoji: '✨' },
          { id: 'helper', text: 'Helper', emoji: '🤝' },
          { id: 'learner', text: 'Learner', emoji: '🧠' },
        ],
      },
    ],
  },
  {
    id: 'demo-adult',
    title: 'Experience Feedback',
    description: "Share your thoughts on today's session. Takes under 2 minutes.",
    emoji: '📋',
    color: '#14B8A6',
    audience: 'adult',
    is_active: true,
    response_count: 0,
    completion_rate: 0,
    created_at: '2026-04-26T00:00:00Z',
    questions: [
      {
        id: 'daq1',
        text: "How satisfied were you with today's experience?",
        type: 'scale',
        required: true,
        points: 0,
        options: [
          { id: '1', text: '1 — Very dissatisfied', emoji: '' },
          { id: '2', text: '2', emoji: '' },
          { id: '3', text: '3 — Neutral', emoji: '' },
          { id: '4', text: '4', emoji: '' },
          { id: '5', text: '5 — Very satisfied', emoji: '' },
        ],
      },
      {
        id: 'daq2',
        text: 'What was most helpful?',
        type: 'multiple_choice',
        required: true,
        points: 0,
        options: [
          { id: 'content', text: 'The content and curriculum', emoji: '' },
          { id: 'staff', text: 'The staff and facilitators', emoji: '' },
          { id: 'community', text: 'Connecting with others', emoji: '' },
          { id: 'resources', text: 'Resources and materials', emoji: '' },
          { id: 'structure', text: 'The structure and pacing', emoji: '' },
        ],
      },
      {
        id: 'daq3',
        text: 'What would you improve?',
        type: 'multiple_choice',
        required: true,
        points: 0,
        options: [
          { id: 'timing', text: 'Session timing and length', emoji: '' },
          { id: 'communication', text: 'Communication beforehand', emoji: '' },
          { id: 'activities', text: 'Activities and engagement', emoji: '' },
          { id: 'space', text: 'The physical environment', emoji: '' },
          { id: 'nothing', text: 'Nothing — it was great!', emoji: '' },
        ],
      },
    ],
  },
];

// Merge demo surveys into lookups
const ALL_SURVEYS = [...SAMPLE_SURVEYS, ...DEMO_SURVEYS];

export function getSurveyById(id: string): Survey | undefined {
  return ALL_SURVEYS.find((s) => s.id === id);
}

export function getResultsById(id: string): ResultSummary[] {
  return SAMPLE_RESULTS[id] ?? [];
}
